### ISSUE TITLE
Chef-Container work with docker version 1.1.2 ?

### ISSUE THREAD

**Issue by snayakie** [chef-boneyard/chef-init#25]
Hi, I upgrade to Docker version 1.1.2, build d84a070/1.1.2
on my RHEL 6.5 host today. Had Docker 1.0.0 previously.

After that, I installed "# chef gem install knife-container" again, which has given me knife-container-0.2.4.

Seeing some strange issues which I wasn't seeing until today in previous runs, like in my container runtime, I'm not seeing a directory of my software , e.g., /opt/tnpfa/log , which was there before.

Just to confirm - is chef container tested with docker 1.1.2 ?

**Comment by tduffield** [comment]
It hasn't been but that shouldn't really matter. Are you using boot2docker?

**Comment by snayakie** [comment]
Not using boot2docker.

**Comment by tduffield** [comment]
chef-init has no knowledge or interaction with Docker and knife-container leverages the Docker API directly which hasn't changed much (if any) since 1.0.0. I have tested knife-container against v1.14 of the Docker Remote API. 

I'm not sure why you are seeing what you are seeing. You may need to rebuild your Docker images. If you can point to a specific resource that is failing or misbehaving I might be able to help you further but based on the information you've provided I cannot help you. Sorry.

**Comment by snayakie** [comment]
Understood, I'll keep an eye.
